In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style("whitegrid")

import scipy
from scipy import stats

from src.features.build_features import df, X, X_tfidf,vocabulary

array([0, 0, 0, ..., 0, 0, 0])

In [68]:
tmp = np.asarray(X.sum(axis=0)).reshape(-1)*np.asarray(X[0,:].todense()).reshape(-1)


482544

array(<1x24976 sparse matrix of type '<class 'numpy.int64'>'
	with 91 stored elements in Compressed Sparse Row format>, dtype=object)

In [112]:
tmp2 = tmp/tmp.sum()
np.where(tmp2 > 0)

(array([   15,   211,   246,   827,  1026,  1388,  1998,  2148,  2202,
         2485,  3371,  3449,  3489,  3861,  3953,  4526,  4648,  4682,
         5706,  5785,  6294,  6326,  6335,  6550,  6744,  7234,  7553,
         7572,  7636,  7637,  8114,  8244,  8382,  8383,  9217,  9251,
         9845,  9921, 10211, 10480, 10602, 11026, 11092, 11236, 11702,
        11742, 11769, 11937, 12567, 13244, 14131, 14323, 14461, 15208,
        15235, 15776, 15936, 16127, 16230, 17123, 17341, 17926, 18259,
        18277, 18332, 18645, 18670, 18711, 18714, 18912, 19141, 19545,
        19632, 20496, 20514, 20844, 20937, 21228, 21232, 21544, 22078,
        22379, 22466, 22494, 22747, 22879, 23144, 23326, 23342, 24031,
        24471]),)

In [114]:
np.sort(tmp2)[::-1]

array([0.09563066, 0.07643241, 0.05271022, ..., 0.        , 0.        ,
       0.        ])

In [115]:
np.argsort(tmp2)[::-1]

array([ 8382, 23326,  3489, ..., 16637, 16638,     0])

In [117]:
id2word = {v:k for v, k in sorted((value, key) for (key,value) in vocabulary.items())}
id2word.get(23326)

'ung'

In [90]:
df.iloc[0].Tekst

'Før jeg afslutter min redegørelse, vil jeg gerne rette en dybfølt tak til den grønlandske befolkning. Det var med stor glæde, jeg var med til at fejre selvstyret i Grønland den 21. juni. Det var en smuk dag. Jeg havde også fornøjelsen af at dele den med en række af mine kolleger. Det var en smuk dag, hvor Grønland så fremad. Man kunne simpelt hen mærke troen på en fremtid med muligheder for at påtage sig ansvar for nye samfundsopgaver.Både i forhold til Grønland og til Færøerne fører regeringen en politik, der bygger på overdragelse af ansvar, så langt mulighederne tillader, og så langt de grønlandske og færøske ønsker rækker. Færøerne har gennem de seneste år overtaget ansvar på en række områder, og Grønland er nu godt i gang med sine forberedelser.Vi løsner de bånd i rigsfællesskabet, som snærer, men der er også andre bånd, som i en globaliseret verden kan styrkes, og hvor der kan være en fælles interesse i at styrke dem som under den aktuelle økonomiske krise, hvor regeringens bank

In [109]:
tmp = np.asarray(X.sum(axis=0)).reshape(-1)*np.asarray(X[0,:].todense()).reshape(-1)
np.where(tmp > 0)

(array([   15,   211,   246,   827,  1026,  1388,  1998,  2148,  2202,
         2485,  3371,  3449,  3489,  3861,  3953,  4526,  4648,  4682,
         5706,  5785,  6294,  6326,  6335,  6550,  6744,  7234,  7553,
         7572,  7636,  7637,  8114,  8244,  8382,  8383,  9217,  9251,
         9845,  9921, 10211, 10480, 10602, 11026, 11092, 11236, 11702,
        11742, 11769, 11937, 12567, 13244, 14131, 14323, 14461, 15208,
        15235, 15776, 15936, 16127, 16230, 17123, 17341, 17926, 18259,
        18277, 18332, 18645, 18670, 18711, 18714, 18912, 19141, 19545,
        19632, 20496, 20514, 20844, 20937, 21228, 21232, 21544, 22078,
        22379, 22466, 22494, 22747, 22879, 23144, 23326, 23342, 24031,
        24471]),)

In [38]:
tmp = np.asarray(X.sum(axis=0)).reshape(-1)/X.sum()
tmp

array([1.18171939e-04, 2.45998277e-03, 1.43317677e-06, ...,
       6.77501744e-05, 4.29953030e-06, 4.60049742e-04])

In [27]:
tmp = dict(sorted({v: k for k, v in vocabulary.items()}.items()))
tmp.get(11289)

'kommun'

5434

In [12]:
from collections import Counter
[k for k,v in Counter(X.nonzero()[1]).items() if v >= X.shape[0]*0.1]

[11289]

In [114]:
corpus[2]

[]

In [116]:
cx = scipy.sparse.coo_matrix(X)
corpus = [[] for _ in range(X.shape[0])]
for speech, col, data in zip(cx.row, cx.col, cx.data):
    corpus[speech].append((col, data))

In [77]:
cx.row

array([     0,      0,      0, ..., 183346, 183346, 183346], dtype=int32)

In [78]:
cx.col

array([   27,    72,    94, ..., 23326, 24870, 24871], dtype=int32)

In [37]:
X.shape[0]

183347

In [71]:
corpus[0]

[(27, 1),
 (72, 3),
 (94, 3),
 (107, 1),
 (218, 1),
 (469, 1),
 (518, 1),
 (771, 1),
 (870, 1),
 (951, 1),
 (999, 1),
 (1012, 2),
 (1054, 1),
 (1360, 1),
 (1399, 1),
 (1415, 1),
 (1422, 1),
 (1554, 2),
 (1557, 1),
 (1568, 3),
 (2148, 1),
 (2199, 1),
 (2443, 1),
 (2484, 1),
 (2589, 1),
 (2595, 1),
 (2664, 1),
 (2698, 1),
 (3109, 1),
 (3123, 1),
 (3145, 1),
 (3213, 1),
 (3371, 1),
 (3429, 1),
 (3458, 1),
 (3489, 2),
 (3500, 1),
 (4432, 1),
 (4493, 1),
 (4529, 1),
 (4702, 1),
 (4705, 1),
 (4707, 1),
 (4786, 2),
 (4941, 1),
 (5238, 1),
 (5323, 1),
 (5599, 2),
 (5650, 1),
 (5944, 1),
 (6267, 1),
 (6335, 1),
 (6429, 1),
 (6467, 1),
 (6498, 2),
 (6734, 1),
 (6797, 1),
 (6908, 1),
 (7097, 1),
 (7266, 1),
 (7404, 1),
 (7421, 1),
 (7526, 1),
 (7553, 2),
 (7639, 1),
 (7695, 1),
 (7741, 1),
 (7870, 2),
 (8004, 1),
 (8224, 3),
 (8281, 1),
 (8381, 1),
 (8632, 1),
 (8732, 1),
 (8975, 1),
 (9090, 1),
 (9365, 1),
 (9392, 1),
 (9415, 1),
 (9600, 1),
 (9968, 4),
 (10112, 1),
 (10119, 2),
 (10262, 1),
 (1

In [20]:
cx.row

array([     0,      0,      0, ..., 183346, 183346, 183346], dtype=int32)

In [23]:
cx.data

array([1, 3, 3, ..., 3, 1, 1])

In [11]:
X[0].data

array([ 1,  3,  3,  1,  1,  1,  1,  1,  1,  1,  1,  2,  1,  1,  1,  1,  1,
        2,  1,  3,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  2,  1,  1,  1,  1,  1,  1,  1,  2,  1,  1,  1,  2,  1,  1,  1,
        1,  1,  1,  2,  1,  1,  1,  1,  1,  1,  1,  1,  2,  1,  1,  1,  2,
        1,  3,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  4,  1,  2,  1,  2,
        1,  1,  2,  1,  1,  1,  1,  1,  4,  1,  3,  1,  2,  1,  2,  1,  1,
        1,  1,  1,  1,  2,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  2,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  2,  1,  1,  1,  3,  1,  1,  1,  1,  2,  2,  1,  1,  1,  1,
        1,  1,  1,  1,  2,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  4,  1,  1,  1,  1,  1, 10,  2,  2,  1,  3,  3,  1,
        1,  1,  1,  2,  2,  1,  2,  1])

In [23]:
tmp = pd.DataFrame(data = X, index = df.Dagsordenpunkt, columns = ['kage'])

In [119]:
cancer = np.empty((df.Dagsordenpunkt.nunique(),X.shape[1]))
for i, punkt in enumerate(df.Dagsordenpunkt.unique()):
    if (i % 500) == 0:
        print(i)
    
    try:
        cancer[i,:] = np.minimum(1,np.asarray(sum([s for s in tmp.loc[punkt].kage.values]).todense()).reshape(-1,))
    except AttributeError:
        cancer[i,:] = np.minimum(1,np.asarray(tmp.loc[punkt].kage.todense()).reshape(-1))


0
500
1000
1500
2000
2500
3000
3500
4000
4500
5000
5500
6000
6500
7000


In [164]:
indexes = np.where(cancer.mean(axis=0) > 0.4)[0]

In [216]:
ae = dict(sorted({v: k for k, v in vocabulary.items()}.items()))
for idx in indexes:
    del ae[idx]

voc_new = {word: idx for idx, word in enumerate(list(ae.values()))}
voc_new
#del dict(sorted({v: k for k, v in vocabulary.items()}.items()))[714]

{'00': 0,
 '000': 1,
 '001': 2,
 '01': 3,
 '02': 4,
 '03': 5,
 '04': 6,
 '05': 7,
 '050': 8,
 '06': 9,
 '07': 10,
 '070': 11,
 '08': 12,
 '09': 13,
 '095': 14,
 '10': 15,
 '100': 16,
 '101': 17,
 '102': 18,
 '103': 19,
 '104': 20,
 '105': 21,
 '106': 22,
 '107': 23,
 '108': 24,
 '109': 25,
 '11': 26,
 '110': 27,
 '111': 28,
 '112': 29,
 '113': 30,
 '114': 31,
 '115': 32,
 '116': 33,
 '117': 34,
 '118': 35,
 '119': 36,
 '12': 37,
 '120': 38,
 '121': 39,
 '122': 40,
 '123': 41,
 '124': 42,
 '125': 43,
 '126': 44,
 '127': 45,
 '128': 46,
 '129': 47,
 '12½': 48,
 '13': 49,
 '130': 50,
 '131': 51,
 '132': 52,
 '133': 53,
 '134': 54,
 '135': 55,
 '136': 56,
 '137': 57,
 '138': 58,
 '139': 59,
 '14': 60,
 '140': 61,
 '141': 62,
 '142': 63,
 '143': 64,
 '144': 65,
 '145': 66,
 '146': 67,
 '147': 68,
 '148': 69,
 '149': 70,
 '14½': 71,
 '15': 72,
 '150': 73,
 '151': 74,
 '152': 75,
 '153': 76,
 '154': 77,
 '155': 78,
 '156': 79,
 '157': 80,
 '158': 81,
 '159': 82,
 '16': 83,
 '160': 84,
 '161':

In [169]:
fuckfaces = [{v: k for k, v in vocabulary.items()}.get(x) for x in indexes]
fuckfaces

['afgør',
 'aftal',
 'altså',
 'alvor',
 'ansvar',
 'arbejd',
 'baggrund',
 'bedr',
 'bedst',
 'behandl',
 'behandling',
 'behov',
 'bestemt',
 'betyd',
 'blev',
 'borg',
 'brug',
 'brugt',
 'båd',
 'dag',
 'danmark',
 'dansk',
 'debat',
 'del',
 'desvær',
 'diskussion',
 'diskut',
 'drøft',
 'egent',
 'end',
 'enhedslist',
 'enig',
 'enkelt',
 'faktisk',
 'fald',
 'fast',
 'find',
 'fokus',
 'folk',
 'folkeparti',
 'folketing',
 'forbind',
 'foretag',
 'forhold',
 'form',
 'formand',
 'formål',
 'fornuft',
 'forskel',
 'forslag',
 'forstå',
 'forstår',
 'forsøg',
 'fortsat',
 'forvent',
 'frem',
 'fremtid',
 'fru',
 'fuld',
 'fuldstænd',
 'fået',
 'følg',
 'før',
 'først',
 'gang',
 'gansk',
 'gennemfør',
 'gern',
 'giv',
 'glad',
 'glæd',
 'god',
 'grad',
 'grund',
 'gå',
 'går',
 'gæld',
 'haft',
 'handl',
 'hel',
 'hensyn',
 'hjælp',
 'hold',
 'holdning',
 'hr',
 'hurt',
 'hvert',
 'hvilk',
 'håb',
 'hånd',
 'høj',
 'hør',
 'hørt',
 'ind',
 'initiativ',
 'interes',
 'jam',
 'kald',

In [154]:
print(i/df.Dagsordenpunkt.nunique()*100, "%\r", end='')
print(i/df.Dagsordenpunkt.nunique()*100, "%\r", end ='')

99.98634625887493 %

In [149]:
df.Dagsordenpunkt.nunique()

7324

In [145]:
import scipy

def delete_cols_csr(mat, indices):
    """
    Remove the rows denoted by ``indices`` form the CSR sparse matrix ``mat``.
    """
    if not isinstance(mat, scipy.sparse.csr_matrix):
        raise ValueError("works only for CSR format -- use .tocsr() first")
    indices = list(indices)
    mask = np.ones(mat.shape[1], dtype=bool)
    mask[indices] = False
    return mat[:,mask]

delete_rows_csr(ged, indexes)

<183347x25077 sparse matrix of type '<class 'numpy.int64'>'
	with 6819344 stored elements in Compressed Sparse Row format>

In [222]:
X

<183347x25222 sparse matrix of type '<class 'numpy.int64'>'
	with 10193231 stored elements in Compressed Sparse Row format>

In [223]:
vocabulary

{'danmark': 3910,
 'land': 12374,
 'lev': 12695,
 'byg': 3389,
 'rigt': 18102,
 'samfund': 18479,
 'foretagsom': 6541,
 'opfindsom': 15527,
 'købmandskab': 12280,
 'skabt': 19101,
 'trygt': 22340,
 'gensid': 8071,
 'tillid': 21765,
 'respek': 17877,
 'rim': 18106,
 'bredest': 3139,
 'skuldr': 19511,
 'bær': 3477,
 'størst': 20761,
 'byrd': 3447,
 'ting': 21922,
 'bedr': 2133,
 'selvfølg': 18795,
 'prøv': 17162,
 'træd': 22355,
 'skridt': 19447,
 'skil': 19313,
 'betrag': 2602,
 'ståend': 20724,
 'smukt': 19741,
 'billed': 2712,
 'fyld': 7586,
 'stolt': 20484,
 'folkeslag': 6307,
 'misund': 14245,
 'fantastisk': 5685,
 'bedst': 2144,
 'sted': 20370,
 'verd': 24263,
 'regering': 17591,
 'folketing': 6313,
 'dansk': 3920,
 'folk': 6259,
 'entreprenant': 5271,
 'ingeniør': 10206,
 'idé': 9693,
 'sat': 18645,
 'system': 21135,
 'produktion': 16986,
 'håndværk': 9482,
 'arbejd': 1506,
 'ansæt': 1427,
 'udvid': 23159,
 'virksom': 24514,
 'ansvarsfuld': 1420,
 'skolelær': 19370,
 'øje': 25121,